### ISSUE TITLE
Why aren't functions with math operations considered pure function?

### ISSUE THREAD

**Issue by andrerpena** [MaiaVictor/LJSON#3]
I may be missing something here, but as long as the function depends only on the given parameters, that would be considered a "pure function". Wouldn't it?

**Comment by VictorTaelin** [comment]
Those are perfectly pure functions, but **specific** pure functions. LJSON doesn't add any specific function - just functions themselves, as a feature. For example, JavaScript defines numbers, but doesn't define the Euler constant. `e` is a perfectly valid specific number, just not one defined on the ECMAS specification. If you want to use `e`, you have to define it yourself:

```
e = 0.5772156649
```

In the same way that, if you want to use `+`, you have to define it yourself:

```
function add(a,b){return a + b;}; 
function foo(add,x){
    return add(x,add(x,x));
};
```

It is maybe worth wondering whether it is makes sense to add some primitives to LJSON. The issue is that it is not obvious which functions to include. The mathematical ones are maybe OK. But what about `while`? Adding it would remove the ability to say any first-order program halts. Moreover, do you add `[].concat`, if it is already expressible with just `[].foldr` and `[].cons`? Minimality is an important part of the JSON specification and so is for λJSON. I tend to think that just writing a standard library with the common functions would be more healthy in the long term. After all, every imaginable algorithm is already expressible on λJSON alone.

**Comment by jczimm** [comment]
+1 for a separate, standard library for common primitive operations.

In my opinion, the operators that should be included are:
- Comparison operators (`==`, `!=`, `===`, `!==`, `>`, `>=`, `<`, `<=`)
- Arithmetic operators (`+`, `-`, `++`, `--`, `%`)
- Logical operators (`&&`, `||`, `!`)
- Ternary operator (`c ? a : b`)
- `typeof` Unary operator

**Comment by andrerpena** [comment]
@MaiaVictor. You are saying that using JavaScript defined operators will make the function pure but specific because it depends on what the JavaScript specification offers. Yes, I understand. 

I'm thinking of using LJSON as a way of letting the user to define metadata functions on [react-metaform](https://github.com/gearz-lab/react-metaform).

I can live with the fact that the user would need to use provided functions for math ops (sum, multiply...), but, in my case, the functions must have a very defined signature.

This would be valid for LJSON, wouldn't it?

```
function(model, ops) {
       return ops.sum(model.dollarAmount, 100);
}
```

@ckknight, I'm all for it too.

**Comment by VictorTaelin** [comment]
Nope, the `.` is a specific JavaScript operator and isn't part of the JSON specs too. Maybe this pattern would help you?

```
// Gives a specific set of primitives to a LJSON function
function withPrimitives(primitives, fn){
    return fn(function(primName){ return primitives[primName] });
};
```

Your primitives:

```
   var prims = {
        sum : function(a,b){ return a+b; }, // addition
        get : function(obj,attr){ return obj[attr]; } // object access
   };
```

Your user serializes a function like that:

```
userFuncStr = LJSON.stringify(function(P){ // P stands for "primitive"
    return function(model){
        return P("sum")(P("get")(model,"dollarAmount"), 100);
    });
});
```

You use it like so:

```
userFunc = withPrimitives(prims, LJSON.parse(userFuncStr));
```

I'm not sure how this could be improved.
